import type { Metadata } from "next";
<<<<<<< Updated upstream
import { Geist, Geist_Mono } from "next/font/google";
=======
import { Inter, JetBrains_Mono, Plus_Jakarta_Sans } from "next/font/google";
>>>>>>> Stashed changes
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
<<<<<<< Updated upstream
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
=======
      className={`${inter.variable} ${jetbrainsMono.variable} ${plusJakarta.variable} h-full`}
      suppressHydrationWarning
>>>>>>> Stashed changes
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
